var recentStories = {
    'resourceLocation': 'indexDb',
    'name': 'recentStoriesDataModel',
    'maxAllowed': 40,
    name: 'div',
    class: 'container row full-width',
    recentStoriesCollection: {
        name: 'span',
        
        class: 'container row full-width justify_SpaceBetween',
        id: 'recentStoriesCollectionView',
        ehhColors: {
            name: 'span',
            class: 'container card',
            //   collection:['recentStories'],
            title: 'ehh colors',
            thumbnail: '',
            lastEditedat: '',
            createdAt: '',
            author: '',
            collaboratorsId: [],
            location: '',
        },
        ehhDataSet: {
            name: 'span',
            class: 'container card',
            //   collection:['recentStories'],
            title: 'ehh dataSet',
            thumbnail: '',
            lastEditedat: '',
            createdAt: '',
            author: '',
            collaboratorsId: [],
            location: '',
        },
        materialDesignkit: {
            name: 'span',
            class: 'container card',
            //   collection:['recentStories'],
            title: 'material design kit',
            thumbnail: '',
            lastEditedat: '',
            createdAt: '',
            author: '',
            collaboratorsId: [],
            location: '',
        },
        shunyaWebContent: {
            name: 'span',
            class: 'container card',
            //   collection:['recentStories'],
            title: 'shunya.ek webContent',
            thumbnail: '',
            lastEditedat: '',
            createdAt: '',
            author: '',
            collaboratorsId: [],
            location: '',
        },
    },
  
}
